### PR TITLE
Epinowcast example

### PR DESCRIPTION
**Pull request by seabbs**
I've started adding an `epinowcast` example. Pretty crazy data, in particular the most recent data which just has no recent onsets? 

Planning on: 

- [x] Adding a simple nowcast
- [x] A lessons learned nowcast
- [x] Pulling out the underlying reporting distribution
- [x] Maybe estimating Rt using `EpiNow2`

### CODE REVIEW

**Comment by seabbs** [comment]
First draft of this is in place now though a bit rough and ready.

**Comment by seabbs** [comment]
There may be a bug in the code used to extract or plot the CMF. I can't believe it should have no uncertainty. 

https://github.com/epiforecasts/nowcasting.example/blob/52c7fed2cbb70b9bd54ae376a8b481450945b5f3/inst/reports/epinowcast.Rmd#L286

Note I updated the data generating script to use the maximum delay variable you defined in order to keep the length of the delay distribution constant across results. Whilst playing with this I updated and reran a few times. The results in terms of CMF recovery are quite dependent on the seed as might be expected with such low numbers.

**Comment by sbfnk** [comment]
Looks good - some suggested edits coming in a separate PR.

**Comment by seabbs** [comment]
I need to look again to see what is happening to the credible intervals in the CMF plot then I think this is okay to merge.

**Comment by sbfnk** [comment]
Great - when you do I suggest a squash merge do reduce overhead from multiple re-rendering of figures.

**Comment by sbfnk** [comment]
What was the final word on the CMF credible intervals?

**Comment by seabbs** [comment]
I felt a bit full of rage to check and thought I would circle back in another PR.

**Pull request merged**
